[main]
name = "CMGAN"
seed = 42
epochs = 2
cut_len = 32000
save_model_dir = "./save_model"
use_amp = false # whether to use Automatic precision to speed up 
device_ids = "0"
sr = 16000
interval_eval = 1
resume = false
max_clip_grad_norm = 5.0 # torch.nn.utils.max_clip_grad_norm
num_prints = 5
    
    [main.loss_weights]
    ri = 0.1
    mag = 0.9
    time = 0.2  
    gan =  0.05

[model]
num_channel = 64

[feature]
n_fft = 400
hop = 100
ndf = 16

[dataset_train]
path = "/home/minhkhanh/Desktop/work/denoiser/dataset/sub_voice_bank_demand/test"
    [dataset_train.dataloader]
    batchsize = 1
    n_worker = 16
    pin_memory = true

    [dataset_train.sampler]
    shuffle = true 
    drop_last = true
    
[dataset_valid]
path = "/home/minhkhanh/Desktop/work/denoiser/dataset/sub_voice_bank_demand/test"
    
    [dataset_valid.dataloader]
    n_worker = 16
    batchsize = 1

    [dataset_valid.sampler]
    shuffle = false
    drop_last = false 

[dataset_test]
path = "/home/minhkhanh/Desktop/work/denoiser/dataset/sub_voice_bank_demand/test"


[optimizer]
init_lr = 5e-4

[scheduler]
decay_epoch = 30
gamma = 0.5

[trainer]
path = "trainer.trainer.Trainer"


    
    

