[main]
name = "CMGAN_unet_32_bilinear_discriminator_dilation_kd_logit_remix"
seed = 0
epochs = 100
cut_len = 32000
save_model_dir = "/root/khanhnnm/se/checkpoint"
use_amp = false
use_ZeRo = false
teacher_checkpoint = "/root/khanhnnm/se/cmgan_denoiser/src/best_ckpt/ckpt"
student_model = "Unet32"
sr = 16000
interval_eval = 5
resume = true
max_clip_grad_norm = 2.0
gradient_accumulation_steps = 1
num_prints = 5

[model]
type = "unet"
num_channel = 3

[feature]
n_fft = 400
hop = 100
ndf = 16

[dataset_train]
path = "/root/khanhnnm/se/VCTK/train"

[dataset_valid]
path = "/root/khanhnnm/se/VCTK/test"

[dataset_test]
path = "/root/khanhnnm/se/VCTK/test"

[optimizer]
init_lr = 0.005

[scheduler]
decay_epoch = 20
gamma = 0.5

[trainer]
path = "trainer.kd_trainer_final_discriminator.KDTrainer"

[main.augment]
remix = true
remix_snr = false

[main.loss_weights]
ri = 0.1
mag = 0.9
time = 0.2
gan = 0.05

[main.criterion]
KDLoss = true
AFDLoss = false
AKD = false
FAKD = false
UCLFWPKD = false
kd_weight = [ 1.0,]

[dataset_train.dataloader]
batchsize = 16
n_worker = 4
pin_memory = true

[dataset_train.sampler]
shuffle = true
drop_last = true

[dataset_valid.dataloader]
batchsize = 16
n_worker = 4

[dataset_valid.sampler]
shuffle = true
drop_last = false
